### ISSUE TITLE
Use branches and pull requests in workflow.

### ISSUE THREAD

**Issue by miqid** [learntocodemeetup/flaming-octo-wallhack#1]
Once everyone is comfortable with the basics of reading history (i.e. `status`, `log`), creating commits (i.e. `add`), synchronising them locally (i.e. `fetch`, `pull`), and publishing them (i.e. `push`), it's time to take it one step further and involve the concept of branches and pull requests. These two things help keep a project code base sane by facilitating a more streamlined workflow. There's also the idea of forking, but let's revisit that another time.

Workflow is flexible and driven by how a development team wants to work. However, I find that for small projects and teams, making everybody develop in their own branch and then submitting a pull request back into the main branch (i.e. `master`) is a good simple way to go. Without going into much detail here, keeping the main branch stable and using pull requests to gate changes (i.e. requiring code review from other team members) reduces the situation where the main code base goes catastrophically wrong (and potential burning of culprits at the stake).

Consider this a topic to review in a future meet up.

**Comment by nii236** [comment]
Can you think of a good simple project idea for demonstrating branching?

**Comment by miqid** [comment]
I think before one can fully appreciate branches and pull requests, conflict resolution will need to be explained (i.e. `merge` and possibly `rebase` for the brave).

**Comment by miqid** [comment]
Completed rough guide to address this issue.

See this [branch](https://github.com/learntocodemeetup/flaming-octo-wallhack/tree/topic-branch-merge-pr).
